name: tekton_core
description: "Kit base compartilhado entre projetos Flutter: widgets, formatters e utilitários."
version: 0.2.0
publish_to: 'none'
repository: https://github.com/leandrorochaadm/tekton_core

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
